// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7YyvT3zWLYiOHA-2lOh0yck9rBxUMEio',
    appId: '1:365434793152:web:c053495efbfa75c0941125',
    messagingSenderId: '365434793152',
    projectId: 'pushnotitest-c572b',
    authDomain: 'pushnotitest-c572b.firebaseapp.com',
    storageBucket: 'pushnotitest-c572b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa-VnqKTXotKWZ7s4NvWsi_W5T0mo1l4M',
    appId: '1:365434793152:android:2b975af1bcee71b5941125',
    messagingSenderId: '365434793152',
    projectId: 'pushnotitest-c572b',
    storageBucket: 'pushnotitest-c572b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcvM9AreicQBxkPO5g_SuiU1f9jWlAT6M',
    appId: '1:365434793152:ios:7bbac1e5c8d32878941125',
    messagingSenderId: '365434793152',
    projectId: 'pushnotitest-c572b',
    storageBucket: 'pushnotitest-c572b.appspot.com',
    iosBundleId: 'com.example.flutterNotiProj1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcvM9AreicQBxkPO5g_SuiU1f9jWlAT6M',
    appId: '1:365434793152:ios:7bbac1e5c8d32878941125',
    messagingSenderId: '365434793152',
    projectId: 'pushnotitest-c572b',
    storageBucket: 'pushnotitest-c572b.appspot.com',
    iosBundleId: 'com.example.flutterNotiProj1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7YyvT3zWLYiOHA-2lOh0yck9rBxUMEio',
    appId: '1:365434793152:web:b52cf7a4f57695d6941125',
    messagingSenderId: '365434793152',
    projectId: 'pushnotitest-c572b',
    authDomain: 'pushnotitest-c572b.firebaseapp.com',
    storageBucket: 'pushnotitest-c572b.appspot.com',
  );
}
